### ISSUE TITLE
<Android> App is crashing when press Connect button </Android>

### ISSUE THREAD

**Issue by algotechnologies** [freshplanet/ANE-Facebook#228]
Please help !

**Comment by skliarovartem** [comment]
same here

**Comment by hybridmindset** [comment]
Yea this just crashes on Android after calling openSessionWithReadPermissions method

**Comment by amhofny** [comment]
check this version, it uses AIR 18.0 and compiled for both IOS and Android, it is based on @wastedabuser changes
https://github.com/amhofny/ANE-Facebook

**Comment by st15** [comment]
I used https://github.com/amhofny/ANE-Facebook but to make it work I added the following activities in the application descriptor, as suggested in [issue #190](https://github.com/freshplanet/ANE-Facebook/issues/190):

    <activity android:name="com.facebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="@string/app_name" />
    <activity android:name="com.freshplanet.ane.AirFacebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"></activity>
    <activity android:name="com.freshplanet.ane.AirFacebook.WebDialogActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"></activity>

That is WebDialogActivity instead of DialogActivity.

**Comment by hybridmindset** [comment]
I still can't get this thing to work. The app just stops. I also get the following warning when packaging the APK. 

[java] Warning: Resource values-he/strings.xml has been skipped because of mismatch with supported languages information in application descriptor.

[java] Warning: Resource values-iw/strings.xml has been skipped because of mismatch with supported languages information in application descriptor.

Are we not suppose to use Java version 1.6 to compile?

**Comment by flashmandv** [comment]
I'm so sick of these crashes..There isn't a good ANE that works..they all have problems or crash..I started forking @wastedabuser 's ane because it was the closest of working..but it crashes the same way (sometimes).
My Adobe AIR currently uses one actioonscript sdk (modified by me) which uses StageWebView and on the first user login opens the login with StageWebView browser..but I want to replace it because the native one will allow my users to enter without typing their password and email.. 
But I don't know anymore..these ANE's are so buggy and maybe I will upload my current web view solution so you can use it (at least it works every time)

**Comment by ventr1x** [comment]
Yeah, simply does not work on Android atm.
Also the docs are not up to date at all.

The linked alternative also does not work as it throws masses of errors while packaging.
